### PR TITLE
feat(github): add access token configuration for GitHub client

### PR DESCRIPTION
**Pull request by karmingc**
duplicate of https://github.com/AaronFriel/go-change/pull/20, thinking through, I'd much prefer to contribute to this repository rather than maintaining my own fork. Open to any feedbacks.

### CODE REVIEW

**Comment by karmingc** [comment]
@AaronFriel, requesting your review when you have a moment. Thanks!

**Review by AaronFriel — APPROVED** [review]
Thanks for submitting this PR!

**Comment by AaronFriel** [comment]
bors retry

**Comment by karmingc** [comment]
@AaronFriel I'll close this one and follow up with another PR. I noticed that the markdown.go uses a hardcoded pulumi/pulumi URL so I'll need to refactor a bit so I can reuse it for other public repositories, potentially leveraging the `GITHUB_REPOSITORY` env. Thanks for review!

**Pull request closed without merging**
